# Configuration for Azure Pipelines
################################################################################

# Only build the master branch, tags and PRs (on by default) to avoid building
# random branches in the repository until a PR is opened
trigger:
  branches:
    include:
    - master
    - refs/tags/*

variables:
  # global variables to enable/disable jobs
  TEST_FEDORA   : false
  TEST_CENTOS   : false
  TEST_WINDOWS  : false
  # other global variables
  # disable auto-display of figures
  GMT_END_SHOW  : off
  # GMT version
  GMT_VERSION   : 6.1.1


jobs:

# Windows installer
################################################################################
- job:
  displayName: 'Windows'
  condition: eq(variables['TEST_WINDOWS'], true)

  pool:
    vmImage: 'windows-2019'

  strategy:
    matrix:
      x86:
        arch: 'win32'
      x64:
        arch: 'win64'

  variables:
    GMT_INSTALLER_URL: https://github.com/GenericMappingTools/gmt/releases/download/6.1.1/gmt-6.1.1-$(ARCH).exe

  steps:
  - bash: bash install-gmt-windows.sh
    displayName: Install GMT via installers

  - powershell: |
      Write-Host "##vso[task.prependpath]C:\programs\gmt6\bin"
      Write-Host "##vso[task.prependpath]C:\Program Files\GraphicsMagick-1.3.32-Q8"
    displayName: Set PATH

  - bash: bash test-gmt.sh
    displayName: Run tests

  - script: call test-gmt.bat
    displayName: Run Batch tests
