# Configuration for Azure Pipelines
################################################################################

# Only build the master branch, tags and PRs (on by default) to avoid building
# random branches in the repository until a PR is opened
trigger:
  branches:
    include:
    - master
    - refs/tags/*

jobs:

# macOS | Install GMT via Bundle
################################################################################
- job:
  displayName: 'macOS | Install GMT via Bundle'

  pool:
    vmImage: 'macOS-10.14'

  steps:
  - bash: source install-gmt-via-bundle.sh
    displayName: Install GMT via Bundle

  - bash: |
      echo "##vso[task.setvariable variable=GMTHOME]/Applications/GMT-6.0.0.app/Contents/Resources"
      echo "##vso[task.setvariable variable=PROJ_LIB]$GMTHOME/share/proj6"
      echo "##vso[task.setvariable variable=MAGICK_CONFIGURE_PATH]$GMTHOME/lib/GraphicsMagick-1.3.33/config"
      echo "##vso[task.setvariable variable=PATH]$GMTHOME/bin:$PATH"
    displayName: Set enviromental variables and PATH

  - bash: |
      echo ${PATH}
      bash test-gmt.sh
    displayName: Run tests
