# This workflow test GMT releases on various platforms

name: Test GMT releases

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

env:
  TEST_BUNDLE: true
  # The GMT version we're testing
  GMT_VERSION: 6.1.1
  GMT_BUNDLE_URL: https://github.com/GenericMappingTools/gmt/releases/download/6.1.1/gmt-6.1.1-darwin-x86_64.dmg

jobs:
  macos-bundle:
    name: Bundle - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-10.15, macOS-11.0]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install via Bundle
        run: |
          bash install-gmt-via-bundle.sh
          GMTHOME=/Applications/GMT.app/Contents/Resources
          echo "PROJ_LIB=${GMTHOME}/share/proj6" >> $GITHUB_ENV
          echo "MAGICK_CONFIGURE_PATH=${GMTHOME}/lib/GraphicsMagick/config" >> $GITHUB_ENV
          echo "${GMTHOME}/bin" >> $GITHUB_PATH

      - name: Run tests
        run: bash test-gmt.sh

  macos-homebrew:
    name: Homebrew - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-10.15, macOS-11.0]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install via Homebrew
        run: bash install-gmt-via-homebrew.sh

      - name: Run tests
        run: bash test-gmt.sh

  macos-macports:
    name: MacPorts - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-10.15, macOS-11.0]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install via MacPorts
        run: |
          bash install-gmt-via-macports.sh
          echo "/opt/local/bin" >> $GITHUB_PATH

      - name: Run tests
        run: bash test-gmt.sh

  conda:
    name: Conda - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v1.7.0
        with:
          python-version: 3.8
          channels: conda-forge
          miniconda-version: "latest"

      - name: Install GMT
        shell: bash -l {0}
        run: conda install --yes --quiet gmt --channel conda-forge

      - name: Run tests
        shell: bash -l {0}
        run: bash test-gmt.sh

      - name: Run Batch tests
        shell: bash -l {0}
        run: call test-gmt.bat
        if: runner.os == 'Windows'
