# This workflow test GMT releases on various platforms

name: Test GMT releases

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

env:
  # The GMT version we're testing
  GMT_VERSION: 6.1.1
  # disable auto-display of figures
  GMT_END_SHOW: off
  # URLs
  GMT_BUNDLE_URL: https://github.com/GenericMappingTools/gmt/releases/download/6.1.1/gmt-6.1.1-darwin-x86_64.dmg

jobs:
  cache-data:
    # Linux and Windows hosts of GitHub Actions can not aceess GMT data
    name: Cache
    runs-on: macos-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install via Bundle
        run: |
          bash install-gmt-via-bundle.sh
          GMTHOME=/Applications/GMT.app/Contents/Resources
          echo "PROJ_LIB=${GMTHOME}/share/proj6" >> $GITHUB_ENV
          echo "MAGICK_CONFIGURE_PATH=${GMTHOME}/lib/GraphicsMagick/config" >> $GITHUB_ENV
          echo "${GMTHOME}/bin" >> $GITHUB_PATH

      - name: Download remote data
        run: gmt which -Ga @earth_relief_01d @earth_day_01d

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: gmt-cache
          path: ~/.gmt/server

  macos-bundle:
    name: Bundle - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-10.15, macOS-11.0]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install via Bundle
        run: |
          bash install-gmt-via-bundle.sh
          GMTHOME=/Applications/GMT.app/Contents/Resources
          echo "PROJ_LIB=${GMTHOME}/share/proj6" >> $GITHUB_ENV
          echo "MAGICK_CONFIGURE_PATH=${GMTHOME}/lib/GraphicsMagick/config" >> $GITHUB_ENV
          echo "${GMTHOME}/bin" >> $GITHUB_PATH

      - name: Run tests
        run: bash test-gmt.sh

  macos-homebrew:
    name: Homebrew - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-10.15, macOS-11.0]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install via Homebrew
        run: bash install-gmt-via-homebrew.sh

      - name: Run tests
        run: bash test-gmt.sh

  macos-macports:
    name: MacPorts - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-10.15, macOS-11.0]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install via MacPorts
        run: |
          bash install-gmt-via-macports.sh
          echo "/opt/local/bin" >> $GITHUB_PATH

      - name: Run tests
        run: bash test-gmt.sh

  conda:
    name: Conda - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          python-version: 3.8
          channels: conda-forge
          miniconda-version: "latest"

      - name: Install GMT
        shell: bash -l {0}
        run: conda install --yes gmt graphicsmagick

      # Download cached remote files (artifacts) from GitHub
      - name: Download remote data from GitHub
        uses: dawidd6/action-download-artifact@v2.6.3
        with:
          workflow: ci.yml
          name: gmt-cache
          path: .gmt

      # Move downloaded files to ~/.gmt directory and list them
      - name: Move and list downloaded remote files
        shell: bash -l {0}
        run: |
          mkdir -p ~/.gmt
          mv .gmt/* ~/.gmt
          ls -lh ~/.gmt

      - name: Run tests
        shell: bash -l {0}
        run: bash test-gmt.sh

      - name: Run Batch tests
        shell: bash -l {0}
        run: call test-gmt.bat
        if: runner.os == 'Windows'

  docker:
    name: Docker - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["fedora:31", "fedora:32", "fedora:33", "fedora:rawhide"]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run docker
        run: |
          docker run -e GMT_END_SHOW -e GMT_VERSION -v `pwd`:`pwd` -w `pwd` --rm $(docker_image) /bin/bash -c '
            dnf -yq install dnf-plugins-core
            dnf -yq copr enable genericmappingtools/gmt
            dnf -yq install gmt
            dnf -yq install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
            dnf -yq install GraphicsMagick ffmpeg gdal
            bash test-gmt.sh
          '
