# This workflow test GMT releases on various platforms

name: Test GMT releases

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

env:
  TEST_BUNDLE: true
  # The GMT version we're testing
  GMT_VERSION: 6.1.1
  GMT_BUNDLE_URL: https://github.com/GenericMappingTools/gmt/releases/download/6.1.1/gmt-6.1.1-darwin-x86_64.dmg

jobs:
  macos-bundle:
    name: ${{ matrix.method }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.15, macOS-11.0]
        method: [Bundle, Homebrew]
    env:
      method: ${{ matrix.method }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install via Bundle
        run: |
          bash install-gmt-via-bundle.sh
          GMTHOME=/Applications/GMT.app/Contents/Resources
          echo "PROJ_LIB=${GMTHOME}/share/proj6" >> $GITHUB_ENV
          echo "MAGICK_CONFIGURE_PATH=${GMTHOME}/lib/GraphicsMagick/config" >> $GITHUB_ENV
          echo "${GMTHOME}/bin" >> $GITHUB_PATH
        if: ${{ env.method == "Bundle" }}

      #- name: Install via Homebrew
      #  run: bash install-gmt-via-homebrew.sh
      #  if: env.method == "Homebrew"

      - name: Run tests
        run: bash test-gmt.sh
