# This workflow test GMT releases on various platforms

name: Test GMT releases

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

env:
  # The GMT version we're testing
  GMT_VERSION: 6.1.1
  GMT_BUNDLE_URL: https://github.com/GenericMappingTools/gmt/releases/download/6.1.1/gmt-6.1.1-darwin-x86_64.dmg

jobs:
  macos-bundle:
    name: Test macOS bundle
    runs-on: macos-10.15

    steps:
      # Cancel previous runs that are not completed
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install GMT Bundle
        run: bash install-gmt-via-bundle.sh

      - name: Set environmental variables
        run: |
          GMTHOME=/Applications/GMT.app/Contents/Resources
          echo "PROJ_LIB=${GMTHOME}/share/proj6" >> $GITHUB_ENV
          echo "MAGICK_CONFIGURE_PATH=${GMTHOME}/lib/GraphicsMagick/config" >> $GITHUB_ENV
          echo "${GMTHOME}/bin" >> $GITHUB_PATH

      - name: Run tests
        run: bash test-gmt.sh
