# This workflow test GMT releases on various platforms

name: Test GMT releases

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  macos-bundle:
    name: Test macOS bundle
    runs-on: macOS-10.14

    steps:
      # Cancel previous runs that are not completed
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Check macOS version
        run: sw_vers -productVersion
